name: Check with Sonar
on:
  push:
    branches:
      - master
      - dev
jobs:
  build-jdk17:
    runs-on: ubuntu-latest
    name: Build with Java 17
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk

      - name: Send to Sonarcloud
        run: mvn -B verify sonar:sonar -Dsonar.sources=src/main/java,target/generated-sources/delombok
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}